package com.sap.cx.boosters.commercedbsync.views;

import java.util.Map;
import java.util.Set;

/**
 * Context holder for one table configuration. Object generated by
 * {@link TableViewGenerator}.
 * 
 * @author i303764
 *
 */
public class ViewConfigurationContext {

	private final String additionalWhereClause;
	private final Map<String, String> columnReplacements;
	private final Set<String> originalColumns;
	private final String table;
	private final String view;
	private final String viewColumnPrefix;

	public ViewConfigurationContext(String table, String view, Set<String> originalColumns,
			Map<String, String> columnReplacements, String additionalWhereClause, String viewColumnPrefix) {
		super();
		this.table = table;
		this.view = view;
		this.originalColumns = originalColumns;
		this.columnReplacements = columnReplacements;
		this.additionalWhereClause = additionalWhereClause;
		this.viewColumnPrefix = viewColumnPrefix;
	}

	public String getAdditionalWhereClause() {
		return additionalWhereClause;
	}

	public Map<String, String> getColumnReplacements() {
		return columnReplacements;
	}

	public Set<String> getOriginalColumns() {
		return originalColumns;
	}

	public String getTable() {
		return table;
	}

	public String getView() {
		return view;
	}

	public String getViewColumnPrefix()
	{
		return viewColumnPrefix;
	}
}
